/*
    Boson v1.2 - Grammar analyzer generator

        Author: ict
        Email:  ictxiangxin@hotmail.com
        Site:   https://github.com/ictxiangxin/boson

    These codes are generated by the boson C++ code generator.
        
         0: !name_0 -> !name_0 statement
         1: !name_0 -> ~
         2: !name_1 -> ',' expression
         3: !name_2 -> !name_2 !name_1
         4: !name_2 -> ~
         5: !name_3 -> '+'
         6: !name_3 -> '-'
         7: !name_4 -> !name_3
         8: !name_5 -> '*'
         9: !name_5 -> '/'
        10: !name_6 -> !name_5
        11: arguments -> expression !name_2
        12: calculator -> !name_0
        13: expression -> expression !name_4 expression_high
        14: expression -> expression_high
        15: expression_final -> '(' expression ')'
        16: expression_final -> function
        17: expression_final -> t_number
        18: expression_final -> t_symbol
        19: expression_high -> expression_high !name_6 expression_top
        20: expression_high -> expression_top
        21: expression_top -> expression_final
        22: expression_top -> expression_top '^' expression_final
        23: function -> t_symbol '(' arguments ')'
        24: statement -> function
        25: statement -> t_symbol '=' expression
*/


#include <stack>
#include <vector>
#include <set>
#include <unordered_map>
#include <string>
#include <functional>


class Token {
public:
    Token() = default;

    Token(std::string &text, const int line, std::string &symbol): text(text), line(line), symbol(symbol) {};

    Token(const char *text, const int line, const char *symbol): text(text), line(line), symbol(symbol) {};

    Token(const char *text, const int line, std::string &symbol): text(text), line(line), symbol(symbol) {};

    Token(std::string &text, const int line, const char *symbol): text(text), line(line), symbol(symbol) {};

    std::string text;
    int line = -1;
    std::string symbol;
};


class Tokenizer {
public:
    using lexical_function = std::function<std::string &(std::string &)>;

    Tokenizer() = default;

    std::vector<Token> &token_list() {
        return this->_token_list;
    }

    void skip() {
        this->_skip = true;
    }

    void newline() {
        this->_line++;
    }

    int error_line() {
        return _error_line;
    }

    int no_error_line() {
        return _no_error_line;
    }

    int tokenize(std::string text) {
        this->_token_list.clear();
        this->_line = 1;
        int state = this->_start_state;
        std::string token_string;
        unsigned long index = 0;
        while (index < text.length()) {
            char character = text[index];
            index++;
            bool get_token = false;
            if (this->_non_greedy_state_set.count(state)) {
                get_token = true;
            }
            if (this->_move_table_attribute.count(state)) {
                std::vector<int> &attribute_list = this->_move_table_attribute[state];
                std::vector<std::set<char>> &character_set_list = this->_move_table_character_set[state];
                std::vector<std::vector<std::vector<int>>> &state_range_list = this->_move_table_range_list[state];
                std::vector<int> &next_state_list = this->_move_table_next_state[state];
                unsigned long i;
                for (i = 0; i < attribute_list.size(); i++) {
                    int attribute = attribute_list[i];
                    std::set<char> &character_set = character_set_list[i];
                    std::vector<std::vector<int>> &range_list = state_range_list[i];
                    int next_state = next_state_list[i];
                    bool condition;
                    if (attribute == 2) {
                        condition = !character_set.count(character);
                        for (auto & range : range_list) {
                            condition &= character < range[0] || character > range[1];
                        }
                    } else {
                        condition = character_set.count(character);
                        if (attribute == 1 && this->_character_set.count(character) == 0) {
                            condition = true;
                        }
                        for (auto & range : range_list) {
                            if (condition || (range[0] <= character && character <= range[1])) {
                                condition = true;
                                break;
                            }
                        }
                    }
                    if (condition) {
                        token_string += character;
                        state = next_state;
                        break;
                    }
                }
                if (i == attribute_list.size()) {
                    if (this->_end_state_set.count(state)) {
                        get_token = true;
                    } else {
                        this->_error_line = this->_line;
                        return this->_error_line;
                    }
                }
            } else {
                if (this->_end_state_set.count(state)) {
                    get_token = true;
                } else {
                    this->_error_line = this->_line;
                    return this->_error_line;
                }
            }
            if (get_token) {
                this->_generate_token(state, token_string);
                token_string = "";
                state = this->_start_state;
                index--;
            }
        }
        if (this->_end_state_set.count(state)) {
            this->_generate_token(state, token_string);
        } else {
            throw std::runtime_error("Invalid state.");
        }
        this->_token_list.emplace_back("", this->_line, "$");
        return this->_error_line;
    }

    void lexical_function_entity(std::string &function_name, lexical_function &function) {
        this->_lexical_function[function_name] = function;
    }

private:
    std::vector<Token> _token_list;
    int _line = 1;
    int _error_line = -1;
    int _no_error_line = -1;
    bool _skip = false;
    std::unordered_map<int, std::vector<int>> _move_table_attribute = {
        {0, {0,0,0,0,0,0,0,0,0,0,0,0,0}},
        {14, {0}},
        {11, {0,0}},
        {9, {0}},
        {3, {0}},
        {1, {0}}
    };
    std::unordered_map<int, std::vector<std::set<char>>> _move_table_character_set = {
        {0, {{'\x5f'},{'\x2d'},{},{'\x0a'},{'\x2a'},{'\x20','\x09'},{'\x5e'},{'\x29'},{'\x2b'},{'\x3d'},{'\x2f'},{'\x2c'},{'\x28'}}},
        {14, {{}}},
        {11, {{'\x2e'},{}}},
        {9, {{'\x20','\x09'}}},
        {3, {{'\x0d'}}},
        {1, {{'\x5f'}}}
    };
    std::unordered_map<int, std::vector<std::vector<std::vector<int>>>> _move_table_range_list = {
        {0, {{{'\x41', '\x5a'},{'\x61', '\x7a'}},{},{{'\x30', '\x39'}},{},{},{},{},{},{},{},{},{},{}}},
        {14, {{{'\x30', '\x39'}}}},
        {11, {{},{{'\x30', '\x39'}}}},
        {9, {{}}},
        {3, {{}}},
        {1, {{{'\x30', '\x39'},{'\x41', '\x5a'},{'\x61', '\x7a'}}}}
    };
    std::unordered_map<int, std::vector<int>> _move_table_next_state = {
        {0, {1,2,11,3,4,9,5,6,7,8,10,12,13}},
        {14, {14}},
        {11, {14,11}},
        {9, {9}},
        {3, {15}},
        {1, {1}}
    };
    std::set<char> _character_set = {'\x6f','\x2d','\x72','\x0d','\x76','\x64','\x56','\x4f','\x6d','\x2e','\x54','\x50','\x42','\x69','\x5f','\x78','\x43','\x4c','\x6c','\x33','\x0a','\x71','\x2a','\x55','\x37','\x4a','\x6a','\x67','\x44','\x20','\x53','\x62','\x41','\x49','\x73','\x6e','\x36','\x58','\x52','\x79','\x29','\x5e','\x35','\x2b','\x38','\x59','\x47','\x75','\x70','\x65','\x46','\x63','\x30','\x61','\x4b','\x3d','\x68','\x39','\x09','\x48','\x34','\x4d','\x2f','\x57','\x6b','\x5a','\x31','\x74','\x2c','\x7a','\x28','\x32','\x51','\x66','\x4e','\x45','\x77'};
    int _start_state = 0;
    std::set<int> _end_state_set = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};
    std::unordered_map<int, std::string> _lexical_symbol_mapping = {
        {1, "t_symbol"},
        {2, "!symbol_6"},
        {3, "newline"},
        {4, "!symbol_7"},
        {5, "!symbol_9"},
        {6, "!symbol_3"},
        {7, "!symbol_5"},
        {8, "!symbol_1"},
        {9, "skip"},
        {10, "!symbol_8"},
        {11, "t_number"},
        {12, "!symbol_4"},
        {13, "!symbol_2"},
        {14, "t_number"},
        {15, "newline"}
    };
    std::set<int> _non_greedy_state_set = {};
    std::unordered_map<std::string, std::vector<std::string>> _symbol_function_mapping = {
        {"skip", {"skip"}},
        {"newline", {"skip","newline"}}
    };
    std::unordered_map<std::string, lexical_function> _lexical_function;

    std::string &_invoke_lexical_function(std::string &symbol, std::string &token_string) {
        this->_skip = false;
        if (this->_symbol_function_mapping.count(symbol)) {
            for (const auto& function : this->_symbol_function_mapping[symbol]) {
                if (this->_lexical_function.count(function)) {
                    token_string = this->_lexical_function[function](token_string);
                } else if (function == "skip") {
                    this->skip();
                } else if (function == "newline") {
                    this->newline();
                }
            }
        }
        return token_string;
    }

    void _generate_token(int state, std::string &token_string) {
        std::string symbol;
        if (this->_lexical_symbol_mapping.count(state)) {
            symbol = this->_lexical_symbol_mapping[state];
        } else {
            symbol = "!symbol";
        }
        token_string = this->_invoke_lexical_function(symbol, token_string);
        if (!this->_skip) {
            this->_token_list.emplace_back(token_string, this->_line, symbol);
        }
    }
};


class BosonGrammarNode {
public:
    BosonGrammarNode() = default;

    explicit BosonGrammarNode(std::string &text) {
        this->set_text(text);
    }

    int get_reduce_number() {
        return this->_reduce_number;
    }

    void set_reduce_number(int reduce_number) {
        this->_reduce_number = reduce_number;
    }

    std::string &get_text() {
        return this->_text;
    }

    void set_text(std::string &text) {
        this->_text = text;
    }

    void append(const BosonGrammarNode &item) {
        this->_children.push_back(item);
    }

    void insert(int index, const BosonGrammarNode &item) {
        this->_children.insert(this->_children.begin() + index, item);
    }

    std::vector<BosonGrammarNode> &children() {
        return this->_children;
    }

    BosonGrammarNode &operator[](int index) {
        return this->_children[index];
    }

private:
    int _reduce_number = -1;
    std::string _text;
    std::vector<BosonGrammarNode> _children;
};


class BosonGrammar {
public:
    BosonGrammar() = default;

    BosonGrammarNode &get_grammar_tree() {
        return this->_grammar_tree;
    }

    void set_grammar_tree(BosonGrammarNode &grammar_tree) {
        this->_grammar_tree = grammar_tree;
    }

    int get_error_index() {
        return this->_error_index;
    }

    void set_error_index(int error_index) {
        this->_error_index = error_index;
    }

    int no_error_index() {
        return this->_no_error_index;
    }

private:
    BosonGrammarNode _grammar_tree;
    int _error_index = -1;
    int _no_error_index = -1;
};


template <class T>
class BosonSemanticsNode {
public:
    BosonSemanticsNode() = default;

    explicit BosonSemanticsNode(T data): _data(data) {};

    static BosonSemanticsNode &null_node() {
        static BosonSemanticsNode node;
        return node;
    }

    T &get_data() {
        return this->_data;
    }

    void set_data(T data) {
        this->_data = std::move(data);
    }

    int get_reduce_number() {
        return this->_reduce_number;
    }

    void set_reduce_number(int reduce_number) {
        this->_reduce_number = reduce_number;
    }

    const std::string &get_text() {
        return this->_text;
    }

    void set_text(std::string &text) {
        this->_text = text;
    }

    void append(const BosonSemanticsNode &item) {
        this->_children.push_back(item);
    }

    void insert(int index, const BosonSemanticsNode &item) {
        this->_children.insert(this->_children.begin() + index, item);
    }

    std::vector<BosonSemanticsNode> &children() {
        return this->_children;
    }

    BosonSemanticsNode &operator[](int index) {
        return this->_children[index];
    }

protected:
    int _reduce_number = -1;
    std::string _text;
    std::vector<BosonSemanticsNode> _children;
    T _data;
};


class GrammarAnalyzer {
public:
    GrammarAnalyzer() = default;

    BosonGrammar grammar_analysis(std::vector<Token> token_list) {
        BosonGrammar grammar;
        std::stack<int> analysis_stack;
        std::stack<BosonGrammarNode> symbol_stack;
        analysis_stack.push(0);
        int token_index = 0;
        while (token_index < token_list.size()) {
            Token &token = token_list[token_index];
            int current_state = analysis_stack.top();
            std::string operation = "e";
            int terminal_index = this->_terminal_index[token.symbol];
            if (this->_action_table.count(current_state)) {
                std::unordered_map<int, std::string> &actions = this->_action_table[current_state];
                if (actions.count(terminal_index)) {
                    operation = actions[terminal_index];
                }
            }
            char operation_flag = operation[0];
            if (operation_flag == 'e') {
                grammar.set_error_index(token_index);
                return grammar;
            } else if (operation_flag == 's') {
                int state_number = (int) strtol(operation.c_str() + 1, nullptr, 10);
                analysis_stack.push(state_number);
                token_index++;
                BosonGrammarNode grammar_node(token.text);
                symbol_stack.push(grammar_node);
            } else if (operation_flag == 'r') {
                int statement_index = (int) strtol(operation.c_str() + 1, nullptr, 10) - 1;
                int reduce_sum = this->_reduce_symbol_sum[statement_index];
                for (int i = 0; i < reduce_sum; i++) {
                    analysis_stack.pop();
                }
                current_state = analysis_stack.top();
                int current_non_terminal_index = this->_reduce_to_non_terminal_index[statement_index];
                int goto_next_state = -1;
                if (this->_goto_table.count(current_state)) {
                    std::unordered_map<int, int> &goto_table = this->_goto_table[current_state];
                    if (goto_table.count(current_non_terminal_index)) {
                        goto_next_state = goto_table[current_non_terminal_index];
                    }
                }
                if (goto_next_state == -1) {
                    throw std::runtime_error("Invalid goto action.");
                }
                analysis_stack.push(goto_next_state);
                if (this->_node_table.count(statement_index)) {
                    std::vector<BosonGrammarNode> symbol_package;
                    for (int i = 0; i < reduce_sum; i++) {
                        symbol_package.insert(symbol_package.begin(), symbol_stack.top());
                        symbol_stack.pop();
                    }
                    symbol_stack.push(this->_generate_grammar_tuple(statement_index, this->_node_table[statement_index], symbol_package));
                } else if (this->_none_grammar_tuple_reduce.count(statement_index)) {
                    BosonGrammarNode grammar_node;
                    for (int i = 0; i < reduce_sum; i++) {
                        grammar_node.insert(0, symbol_stack.top());
                        symbol_stack.pop();
                    }
                    grammar_node.set_reduce_number(statement_index);
                    symbol_stack.push(grammar_node);
                } else {
                    throw std::runtime_error("Invalid reduce number.");
                }
            } else if (operation_flag == 'a') {
                grammar.set_grammar_tree(symbol_stack.top());
                return grammar;
            } else {
                throw std::runtime_error("Invalid action.");
            }
        }
        throw std::runtime_error("Analyzer unusual exit.");
    }

private:
    std::unordered_map<std::string, int>_terminal_index = {
        {"$", 0},
        {"!symbol_7", 1},
        {"!symbol_2", 2},
        {"t_number", 3},
        {"!symbol_5", 4},
        {"!symbol_4", 5},
        {"!symbol_9", 6},
        {"!symbol_1", 7},
        {"t_symbol", 8},
        {"!symbol_6", 9},
        {"!symbol_3", 10},
        {"!symbol_8", 11}
    };
    
    std::unordered_map<int, std::unordered_map<int, std::string>> _action_table = {
        {0, {{0, "r2"}, {8, "r2"}}}, 
        {1, {{0, "r13"}, {8, "s4"}}}, 
        {2, {{0, "a"}}}, 
        {3, {{0, "r1"}, {8, "r1"}}}, 
        {4, {{2, "s7"}, {7, "s6"}}}, 
        {5, {{0, "r25"}, {8, "r25"}}}, 
        {6, {{2, "s9"}, {3, "s15"}, {8, "s13"}}}, 
        {7, {{2, "s9"}, {3, "s15"}, {8, "s13"}}}, 
        {8, {{0, "r21"}, {1, "r21"}, {4, "r21"}, {5, "r21"}, {6, "s18"}, {8, "r21"}, {9, "r21"}, {10, "r21"}, {11, "r21"}}}, 
        {9, {{2, "s9"}, {3, "s15"}, {8, "s13"}}}, 
        {10, {{0, "r26"}, {4, "s20"}, {8, "r26"}, {9, "s21"}}}, 
        {11, {{0, "r15"}, {1, "s26"}, {4, "r15"}, {5, "r15"}, {8, "r15"}, {9, "r15"}, {10, "r15"}, {11, "s24"}}}, 
        {12, {{0, "r22"}, {1, "r22"}, {4, "r22"}, {5, "r22"}, {6, "r22"}, {8, "r22"}, {9, "r22"}, {10, "r22"}, {11, "r22"}}}, 
        {13, {{0, "r19"}, {1, "r19"}, {2, "s7"}, {4, "r19"}, {5, "r19"}, {6, "r19"}, {8, "r19"}, {9, "r19"}, {10, "r19"}, {11, "r19"}}}, 
        {14, {{0, "r17"}, {1, "r17"}, {4, "r17"}, {5, "r17"}, {6, "r17"}, {8, "r17"}, {9, "r17"}, {10, "r17"}, {11, "r17"}}}, 
        {15, {{0, "r18"}, {1, "r18"}, {4, "r18"}, {5, "r18"}, {6, "r18"}, {8, "r18"}, {9, "r18"}, {10, "r18"}, {11, "r18"}}}, 
        {16, {{4, "s20"}, {5, "r5"}, {9, "s21"}, {10, "r5"}}}, 
        {17, {{10, "s29"}}}, 
        {18, {{2, "s9"}, {3, "s15"}, {8, "s13"}}}, 
        {19, {{4, "s20"}, {9, "s21"}, {10, "s31"}}}, 
        {20, {{2, "r6"}, {3, "r6"}, {8, "r6"}}}, 
        {21, {{2, "r7"}, {3, "r7"}, {8, "r7"}}}, 
        {22, {{2, "s9"}, {3, "s15"}, {8, "s13"}}}, 
        {23, {{2, "r8"}, {3, "r8"}, {8, "r8"}}}, 
        {24, {{2, "r10"}, {3, "r10"}, {8, "r10"}}}, 
        {25, {{2, "r11"}, {3, "r11"}, {8, "r11"}}}, 
        {26, {{2, "r9"}, {3, "r9"}, {8, "r9"}}}, 
        {27, {{2, "s9"}, {3, "s15"}, {8, "s13"}}}, 
        {28, {{5, "s35"}, {10, "r12"}}}, 
        {29, {{0, "r24"}, {1, "r24"}, {4, "r24"}, {5, "r24"}, {6, "r24"}, {8, "r24"}, {9, "r24"}, {10, "r24"}, {11, "r24"}}}, 
        {30, {{0, "r23"}, {1, "r23"}, {4, "r23"}, {5, "r23"}, {6, "r23"}, {8, "r23"}, {9, "r23"}, {10, "r23"}, {11, "r23"}}}, 
        {31, {{0, "r16"}, {1, "r16"}, {4, "r16"}, {5, "r16"}, {6, "r16"}, {8, "r16"}, {9, "r16"}, {10, "r16"}, {11, "r16"}}}, 
        {32, {{0, "r14"}, {1, "s26"}, {4, "r14"}, {5, "r14"}, {8, "r14"}, {9, "r14"}, {10, "r14"}, {11, "s24"}}}, 
        {33, {{0, "r20"}, {1, "r20"}, {4, "r20"}, {5, "r20"}, {6, "s18"}, {8, "r20"}, {9, "r20"}, {10, "r20"}, {11, "r20"}}}, 
        {34, {{5, "r4"}, {10, "r4"}}}, 
        {35, {{2, "s9"}, {3, "s15"}, {8, "s13"}}}, 
        {36, {{4, "s20"}, {5, "r3"}, {9, "s21"}, {10, "r3"}}}
    };

    std::unordered_map<int, std::unordered_map<int, int>> _goto_table = {
        {0, {{14, 1}, {15, 2}}}, 
        {1, {{8, 3}, {13, 5}}}, 
        {6, {{3, 11}, {4, 8}, {10, 10}, {11, 12}, {13, 14}}}, 
        {7, {{0, 17}, {3, 11}, {4, 8}, {10, 16}, {11, 12}, {13, 14}}}, 
        {9, {{3, 11}, {4, 8}, {10, 19}, {11, 12}, {13, 14}}}, 
        {10, {{2, 23}, {5, 22}}}, 
        {11, {{6, 25}, {12, 27}}}, 
        {16, {{1, 28}, {2, 23}, {5, 22}}}, 
        {18, {{11, 30}, {13, 14}}}, 
        {19, {{2, 23}, {5, 22}}}, 
        {22, {{3, 32}, {4, 8}, {11, 12}, {13, 14}}}, 
        {27, {{4, 33}, {11, 12}, {13, 14}}}, 
        {28, {{9, 34}}}, 
        {32, {{6, 25}, {12, 27}}}, 
        {35, {{3, 11}, {4, 8}, {10, 36}, {11, 12}, {13, 14}}}, 
        {36, {{2, 23}, {5, 22}}}
    };
    
    std::unordered_map<int, std::string> _node_table = {
        {0, "('*0', '1')"},
        {1, "()"},
        {25, "('0', '2')"},
        {23, "('0', '2')"},
        {3, "('*0', '1')"},
        {4, "()"},
        {11, "('0', ('*1', ('1',)))"},
        {13, "('0', '*1', '2')"},
        {19, "('0', '*1', '2')"},
        {22, "('0', '1', '2')"},
        {15, "('1',)"},
        {18, "('0',)"},
        {17, "('0',)"}
    };

    std::vector<int> _reduce_symbol_sum = {2, 0, 2, 2, 0, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 3, 1, 1, 1, 3, 1, 1, 3, 4, 1, 3};

    std::vector<int> _reduce_to_non_terminal_index = {14, 14, 9, 1, 1, 2, 2, 5, 6, 6, 12, 0, 15, 10, 10, 11, 11, 11, 11, 3, 3, 4, 4, 13, 8, 8};

    std::set<int> _none_grammar_tuple_reduce = {2, 5, 6, 7, 8, 9, 10, 12, 14, 16, 20, 21, 24};

    BosonGrammarNode _generate_grammar_tuple(int statement_index, std::string &node_tuple, std::vector<BosonGrammarNode> &symbol_package) {
        BosonGrammarNode grammar_node;
        int state = 0;
        int sub_start_index = -1;
        bool star = false;
        int parenthesis_count = 0;
        std::string number_text;
        for (size_t i = 1; i < node_tuple.length(); i++) {
            char c = node_tuple[i];
            if (state == 0) {
                if (c == '(') {
                    state = 2;
                } else if (c == '$') {
                    BosonGrammarNode reduce_node;
                    reduce_node.set_reduce_number(statement_index);
                    grammar_node.append(reduce_node);
                } else if (c == '?') {
                    for (auto &node : symbol_package) {
                        grammar_node.append(node);
                    }
                } else if (c == '\'' || c == ',' || c == ' ' || c == ')') {
                    continue;
                } else if (c == '*') {
                    star = true;
                } else if ('0' <= c && c <= '9') {
                    number_text += c;
                    state = 1;
                } else {
                    throw std::runtime_error("Invalid grammar node.");
                }
            } else if (state == 1) {
                if ('0' <= c && c <= '9') {
                    number_text += c;
                } else {
                    i--;
                    int reduce_number = (int) strtol(number_text.c_str(), nullptr, 10);
                    if (star) {
                        for (auto &node : symbol_package[reduce_number].children()) {
                            grammar_node.append(node);
                        }
                    } else {
                        grammar_node.append(symbol_package[reduce_number]);
                    }
                    star = false;
                    number_text = "";
                    state = 0;
                }
            } else if (state == 2) {
                if (c == '*') {
                    star = true;
                } else if (c == '\'' || c == ',' || c == ' ') {
                    continue;
                } else if ('0' <= c && c <= '9') {
                    number_text += c;
                } else {
                    i--;
                    state = 3;
                }
            } else {
                if (c == '(') {
                    if (parenthesis_count == 0) {
                        sub_start_index = i;
                    }
                    parenthesis_count++;
                } else if (c == ')') {
                    parenthesis_count--;
                    if (parenthesis_count == 0) {
                        int reduce_number = (int) strtol(number_text.c_str(), nullptr, 10);
                        std::string sub_node_tuple = node_tuple.substr(sub_start_index, i - sub_start_index + 1);
                        for (auto &each: symbol_package[reduce_number].children()) {
                            BosonGrammarNode sub_node = this->_generate_grammar_tuple(-1, sub_node_tuple, each.children());
                            if (star) {
                                for (auto &node : sub_node.children()) {
                                    grammar_node.append(node);
                                }
                            } else {
                                grammar_node.append(sub_node);
                            }
                        }
                        star = false;
                        number_text = "";
                        state = 0;
                    }
                }
            }
        }
        grammar_node.set_reduce_number(statement_index);
        return grammar_node;
    }
};


template <class T>
class SemanticsAnalyzer {
public:
    using semantic_function = std::function<BosonSemanticsNode<T>(BosonSemanticsNode<T> &)>;

    SemanticsAnalyzer() = default;

    BosonSemanticsNode<T> semantics_analysis(BosonGrammarNode &grammar_tree) {
        return this->_semantics_analysis(grammar_tree);
    }

    static BosonSemanticsNode<T> default_semantics_entity(BosonSemanticsNode<T> &semantics_node) {
        return semantics_node;
    }

    static BosonSemanticsNode<T> naive_semantics_entity(BosonSemanticsNode<T> &semantics_node) {
        if (semantics_node.children().size() == 1) {
            return semantics_node[0];
        } else {
            return semantics_node;
        }
    }

    void semantics_entity(int reduce_number, semantic_function function) {
        std::string reduce_name = "!grammar_" + std::to_string(reduce_number);
        this->semantics_entity(reduce_name, function);
    }

    void semantics_entity(const char *reduce_name, semantic_function function) {
        std::string reduce_name_string(reduce_name);
        this->semantics_entity(reduce_name_string, function);
    }

    void semantics_entity(std::string &reduce_name, semantic_function function) {
        this->_semantics_entity[reduce_name] = function;
    }

private:
    std::unordered_map<int, std::string> _reduce_number_to_grammar_name = {
        {25, "set_variable"}, 
        {23, "function"}, 
        {13, "compute"}, 
        {19, "compute"}, 
        {22, "compute"}, 
        {15, "expression"}, 
        {18, "get_variable"}, 
        {17, "number"}
    };

    std::unordered_map<int, int> _reduce_number_to_grammar_number = {
        {12, 0}, 
        {24, 2}, 
        {11, 4}, 
        {14, 6}, 
        {20, 8}, 
        {21, 10}, 
        {16, 12}
    };

    std::set<int> _naive_reduce_number = {5, 6, 8, 9, 14, 16, 17, 18, 20, 21, 24};

    std::unordered_map<std::string, semantic_function> _semantics_entity;

    BosonSemanticsNode<T> _semantics_analysis(BosonGrammarNode &grammar_tree) {
        std::string grammar_name;
        if (this->_reduce_number_to_grammar_name.count(grammar_tree.get_reduce_number())) {
            grammar_name = this->_reduce_number_to_grammar_name[grammar_tree.get_reduce_number()];
        } else if (this->_reduce_number_to_grammar_number.count(grammar_tree.get_reduce_number())) {
            grammar_name = "!grammar_" + std::to_string(this->_reduce_number_to_grammar_number[grammar_tree.get_reduce_number()]);
        } else {
            grammar_name = "!grammar_hidden";
        }
        BosonSemanticsNode<T> semantics_node;
        for (auto &node: grammar_tree.children()) {
            if (!node.children().empty()) {
                semantics_node.append(this->_semantics_analysis(node));
            } else {
                BosonSemanticsNode<T> temp_node;
                temp_node.set_reduce_number(node.get_reduce_number());
                temp_node.set_text(node.get_text());
                semantics_node.append(temp_node);
            }
        }
        if (this->_semantics_entity.count(grammar_name)) {
            return this->_semantics_entity[grammar_name](semantics_node);
        } else if (this->_naive_reduce_number.count(grammar_tree.get_reduce_number())) {
            return SemanticsAnalyzer::naive_semantics_entity(semantics_node);
        } else {
            return SemanticsAnalyzer::default_semantics_entity(semantics_node);
        }
    }
};
