/*
    Boson v1.3 - Grammar analyzer generator

        Author: ict
        Email:  ictxiangxin@hotmail.com
        Site:   https://github.com/ictxiangxin/boson

    These codes ware generated by the boson C++ code generator.
*/


#include <stack>
#include <vector>
#include <set>
#include <unordered_map>
#include <string>
#include <functional>


class Token {
public:
    Token() = default;

    Token(std::string &text, const int line, std::string &symbol): text(text), line(line), symbol(symbol) {};

    Token(const char *text, const int line, const char *symbol): text(text), line(line), symbol(symbol) {};

    Token(const char *text, const int line, std::string &symbol): text(text), line(line), symbol(symbol) {};

    Token(std::string &text, const int line, const char *symbol): text(text), line(line), symbol(symbol) {};

    std::string text{};
    int line = -1;
    std::string symbol{};
};


class Tokenizer {
public:
    using lexical_function = std::function<std::string &(std::string &)>;

    Tokenizer() = default;

    std::vector<Token> &token_list() {
        return this->_token_list;
    }

    void skip() {
        this->_skip = true;
    }

    void newline() {
        this->_line++;
    }

    int error_line() {
        return _error_line;
    }

    int no_error_line() {
        return _no_error_line;
    }

    int tokenize(std::string text) {
        this->_token_list.clear();
        this->_line = 1;
        int state = this->_start_state;
        std::string token_string{};
        unsigned long index = 0;
        while (index < text.length()) {
            char character = text[index];
            index++;
            bool get_token = false;
            if (this->_non_greedy_state_set.count(state)) {
                get_token = true;
            }
            if (this->_move_table_attribute.count(state)) {
                std::vector<int> &attribute_list = this->_move_table_attribute[state];
                std::vector<std::set<char>> &character_set_list = this->_move_table_character_set[state];
                std::vector<std::vector<std::vector<int>>> &state_range_list = this->_move_table_range_list[state];
                std::vector<int> &next_state_list = this->_move_table_next_state[state];
                unsigned long i;
                for (i = 0; i < attribute_list.size(); i++) {
                    int attribute = attribute_list[i];
                    std::set<char> &character_set = character_set_list[i];
                    std::vector<std::vector<int>> &range_list = state_range_list[i];
                    int next_state = next_state_list[i];
                    bool condition;
                    if (attribute == 2) {
                        condition = !character_set.count(character);
                        for (auto & range : range_list) {
                            condition &= character < range[0] || character > range[1];
                        }
                    } else {
                        condition = character_set.count(character);
                        if (attribute == 1 && this->_character_set.count(character) == 0) {
                            condition = true;
                        }
                        for (auto & range : range_list) {
                            if (condition || (range[0] <= character && character <= range[1])) {
                                condition = true;
                                break;
                            }
                        }
                    }
                    if (condition) {
                        token_string += character;
                        state = next_state;
                        break;
                    }
                }
                if (i == attribute_list.size()) {
                    if (this->_end_state_set.count(state)) {
                        get_token = true;
                    } else {
                        this->_error_line = this->_line;
                        return this->_error_line;
                    }
                }
            } else {
                if (this->_end_state_set.count(state)) {
                    get_token = true;
                } else {
                    this->_error_line = this->_line;
                    return this->_error_line;
                }
            }
            if (get_token) {
                this->_generate_token(state, token_string);
                token_string = "";
                state = this->_start_state;
                index--;
            }
        }
        if (this->_end_state_set.count(state)) {
            this->_generate_token(state, token_string);
        } else {
            throw std::runtime_error("Invalid state.");
        }
        this->_token_list.emplace_back("", this->_line, "$");
        return this->_error_line;
    }

    void register_function(std::string &function_name, lexical_function &function) {
        this->_lexical_function[function_name] = function;
    }

private:
    std::vector<Token> _token_list{};
    int _line = 1;
    int _error_line = -1;
    int _no_error_line = -1;
    bool _skip = false;
    std::unordered_map<int, std::vector<int>> _move_table_attribute = {
        {0, {0,0,0,0,0,0,0,0,0,0,0,0,0}},
        {14, {0}},
        {4, {0}},
        {3, {0}},
        {2, {0,0}},
        {1, {0}}
    };
    std::unordered_map<int, std::vector<std::set<char>>> _move_table_character_set = {
        {0, {{'\x5f'},{},{'\x09','\x20'},{'\x0a'},{'\x3d'},{'\x28'},{'\x29'},{'\x2c'},{'\x2b'},{'\x2d'},{'\x2a'},{'\x2f'},{'\x5e'}}},
        {14, {{}}},
        {4, {{'\x0d'}}},
        {3, {{'\x09','\x20'}}},
        {2, {{},{'\x2e'}}},
        {1, {{'\x5f'}}}
    };
    std::unordered_map<int, std::vector<std::vector<std::vector<int>>>> _move_table_range_list = {
        {0, {{{'\x41', '\x5a'},{'\x61', '\x7a'}},{{'\x30', '\x39'}},{},{},{},{},{},{},{},{},{},{},{}}},
        {14, {{{'\x30', '\x39'}}}},
        {4, {{}}},
        {3, {{}}},
        {2, {{{'\x30', '\x39'}},{}}},
        {1, {{{'\x30', '\x39'},{'\x41', '\x5a'},{'\x61', '\x7a'}}}}
    };
    std::unordered_map<int, std::vector<int>> _move_table_next_state = {
        {0, {1,2,3,4,5,6,7,8,9,10,11,12,13}},
        {14, {14}},
        {4, {15}},
        {3, {3}},
        {2, {2,14}},
        {1, {1}}
    };
    std::set<char> _character_set = {'\x2d','\x78','\x58','\x09','\x28','\x42','\x30','\x47','\x57','\x33','\x37','\x41','\x48','\x6f','\x74','\x31','\x5e','\x52','\x56','\x51','\x73','\x45','\x0a','\x76','\x4e','\x71','\x2e','\x5f','\x4d','\x39','\x6b','\x43','\x2c','\x4f','\x35','\x75','\x6a','\x50','\x59','\x2f','\x72','\x6c','\x32','\x29','\x61','\x20','\x34','\x68','\x46','\x0d','\x65','\x69','\x67','\x4b','\x2a','\x54','\x62','\x64','\x63','\x53','\x49','\x6d','\x2b','\x4c','\x3d','\x55','\x79','\x5a','\x4a','\x70','\x7a','\x66','\x44','\x38','\x6e','\x36','\x77'};
    int _start_state = 0;
    std::set<int> _end_state_set = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};
    std::unordered_map<int, std::string> _lexical_symbol_mapping = {
        {1, "t_symbol"},
        {2, "t_number"},
        {3, "skip"},
        {4, "newline"},
        {5, "!symbol_1"},
        {6, "!symbol_2"},
        {7, "!symbol_3"},
        {8, "!symbol_4"},
        {9, "!symbol_5"},
        {10, "!symbol_6"},
        {11, "!symbol_7"},
        {12, "!symbol_8"},
        {13, "!symbol_9"},
        {14, "t_number"},
        {15, "newline"}
    };
    std::set<int> _non_greedy_state_set = {};
    std::unordered_map<std::string, std::vector<std::string>> _symbol_function_mapping = {
        {"t_symbol", {}},
        {"t_number", {}},
        {"skip", {"skip"}},
        {"newline", {"skip","newline"}}
    };
    std::unordered_map<std::string, lexical_function> _lexical_function{};

    std::string &_invoke_lexical_function(std::string &symbol, std::string &token_string) {
        this->_skip = false;
        if (this->_symbol_function_mapping.count(symbol)) {
            for (const auto& function : this->_symbol_function_mapping[symbol]) {
                if (this->_lexical_function.count(function)) {
                    token_string = this->_lexical_function[function](token_string);
                } else if (function == "skip") {
                    this->skip();
                } else if (function == "newline") {
                    this->newline();
                }
            }
        }
        return token_string;
    }

    void _generate_token(int state, std::string &token_string) {
        std::string symbol;
        if (this->_lexical_symbol_mapping.count(state)) {
            symbol = this->_lexical_symbol_mapping[state];
        } else {
            symbol = "!symbol";
        }
        token_string = this->_invoke_lexical_function(symbol, token_string);
        if (!this->_skip) {
            this->_token_list.emplace_back(token_string, this->_line, symbol);
        }
    }
};


class BosonGrammarNode {
public:
    BosonGrammarNode() = default;

    explicit BosonGrammarNode(std::string &text) {
        this->set_text(text);
    }

    int get_reduce_number() {
        return this->_reduce_number;
    }

    void set_reduce_number(int reduce_number) {
        this->_reduce_number = reduce_number;
    }

    std::string &get_text() {
        return this->_text;
    }

    void set_text(std::string &text) {
        this->_text = text;
    }

    void append(const BosonGrammarNode &item) {
        this->_children.push_back(item);
    }

    void insert(int index, const BosonGrammarNode &item) {
        this->_children.insert(this->_children.begin() + index, item);
    }

    std::vector<BosonGrammarNode> &children() {
        return this->_children;
    }

    BosonGrammarNode &operator[](int index) {
        return this->_children[index];
    }

private:
    int _reduce_number = -1;
    std::string _text{};
    std::vector<BosonGrammarNode> _children{};
};


class BosonGrammar {
public:
    BosonGrammar() = default;

    BosonGrammarNode &get_grammar_tree() {
        return this->_grammar_tree;
    }

    void set_grammar_tree(BosonGrammarNode &grammar_tree) {
        this->_grammar_tree = grammar_tree;
    }

    int get_error_index() {
        return this->_error_index;
    }

    void set_error_index(int error_index) {
        this->_error_index = error_index;
    }

    int no_error_index() {
        return this->_no_error_index;
    }

private:
    BosonGrammarNode _grammar_tree;
    int _error_index = -1;
    int _no_error_index = -1;
};


template <class T>
class BosonSemanticsNode {
public:
    BosonSemanticsNode() = default;

    explicit BosonSemanticsNode(T data): _data(data) {};

    static BosonSemanticsNode &null_node() {
        static BosonSemanticsNode node;
        return node;
    }

    T &get_data() {
        return this->_data;
    }

    void set_data(T data) {
        this->_data = std::move(data);
    }

    int get_reduce_number() {
        return this->_reduce_number;
    }

    void set_reduce_number(int reduce_number) {
        this->_reduce_number = reduce_number;
    }

    const std::string &get_text() {
        return this->_text;
    }

    void set_text(std::string &text) {
        this->_text = text;
    }

    void append(const BosonSemanticsNode &item) {
        this->_children.push_back(item);
    }

    void insert(int index, const BosonSemanticsNode &item) {
        this->_children.insert(this->_children.begin() + index, item);
    }

    std::vector<BosonSemanticsNode> &children() {
        return this->_children;
    }

    BosonSemanticsNode &operator[](int index) {
        return this->_children[index];
    }

protected:
    int _reduce_number = -1;
    std::string _text{};
    std::vector<BosonSemanticsNode> _children{};
    T _data;
};


class Parser {
public:
    Parser() = default;

    BosonGrammar parse(std::vector<Token> token_list) {
        BosonGrammar grammar;
        std::stack<int> analysis_stack;
        std::stack<BosonGrammarNode> symbol_stack;
        analysis_stack.push(0);
        int token_index = 0;
        while (token_index < token_list.size()) {
            Token &token = token_list[token_index];
            int current_state = analysis_stack.top();
            std::string operation = "e";
            int terminal_index = this->_terminal_index_mapping[token.symbol];
            if (this->_sparse_action_table.count(current_state)) {
                std::unordered_map<int, std::string> &actions = this->_sparse_action_table[current_state];
                if (actions.count(terminal_index)) {
                    operation = actions[terminal_index];
                }
            }
            char operation_flag = operation[0];
            if (operation_flag == 'e') {
                grammar.set_error_index(token_index);
                return grammar;
            } else if (operation_flag == 's') {
                int state_number = (int) strtol(operation.c_str() + 1, nullptr, 10);
                analysis_stack.push(state_number);
                token_index++;
                BosonGrammarNode grammar_node(token.text);
                symbol_stack.push(grammar_node);
            } else if (operation_flag == 'r') {
                int statement_index = (int) strtol(operation.c_str() + 1, nullptr, 10);
                int reduce_count = this->_reduce_symbol_count[statement_index];
                for (int i = 0; i < reduce_count; i++) {
                    analysis_stack.pop();
                }
                current_state = analysis_stack.top();
                int current_non_terminal_index_mapping = this->_reduce_non_terminal_index[statement_index];
                int goto_next_state = -1;
                if (this->_sparse_goto_table.count(current_state)) {
                    std::unordered_map<int, int> &goto_table = this->_sparse_goto_table[current_state];
                    if (goto_table.count(current_non_terminal_index_mapping)) {
                        goto_next_state = goto_table[current_non_terminal_index_mapping];
                    }
                }
                if (goto_next_state == -1) {
                    throw std::runtime_error("Invalid goto action.");
                }
                analysis_stack.push(goto_next_state);
                if (this->_sentence_index_grammar_tuple_mapping.count(statement_index)) {
                    std::vector<BosonGrammarNode> symbol_package{};
                    for (int i = 0; i < reduce_count; i++) {
                        symbol_package.insert(symbol_package.begin(), symbol_stack.top());
                        symbol_stack.pop();
                    }
                    BosonGrammarNode grammar_node;
                    for (std::string &node_string : this->_sentence_index_grammar_tuple_mapping[statement_index]) {
                        if (node_string[0] == '*') {
                            int reduce_number = (int) strtol(node_string.c_str() + 1, nullptr, 10);
                            for (BosonGrammarNode &node : symbol_package[reduce_number].children()) {
                                grammar_node.append(node);
                            }
                        } else {
                            int reduce_number = (int) strtol(node_string.c_str(), nullptr, 10);
                            grammar_node.append(symbol_package[reduce_number]);
                        }
                    }
                    grammar_node.set_reduce_number(statement_index);
                    symbol_stack.push(grammar_node);
                } else if (this->_none_grammar_tuple_reduce_set.count(statement_index)) {
                    BosonGrammarNode grammar_node;
                    for (int i = 0; i < reduce_count; i++) {
                        grammar_node.insert(0, symbol_stack.top());
                        symbol_stack.pop();
                    }
                    grammar_node.set_reduce_number(statement_index);
                    symbol_stack.push(grammar_node);
                } else {
                    throw std::runtime_error("Invalid reduce number.");
                }
            } else if (operation_flag == 'a') {
                grammar.set_grammar_tree(symbol_stack.top());
                return grammar;
            } else {
                throw std::runtime_error("Invalid action.");
            }
        }
        throw std::runtime_error("Analyzer unusual exit.");
    }

private:
    std::unordered_map<std::string, int>_terminal_index_mapping = {
        {"!symbol_2", 0},
        {"!symbol_1", 1},
        {"t_symbol", 2},
        {"t_number", 3},
        {"!symbol_3", 4},
        {"!symbol_9", 5},
        {"!symbol_8", 6},
        {"!symbol_4", 7},
        {"!symbol_5", 8},
        {"$", 9},
        {"!symbol_7", 10},
        {"!symbol_6", 11}
    };
    
    std::unordered_map<int, std::unordered_map<int, std::string>> _sparse_action_table = {
        {0, {{2, "r6"}, {9, "r6"}}}, 
        {1, {{9, "a"}}}, 
        {2, {{2, "s4"}, {9, "r7"}}}, 
        {3, {{2, "r15"}, {9, "r15"}}}, 
        {4, {{0, "s7"}, {1, "s6"}}}, 
        {5, {{2, "r17"}, {9, "r17"}}}, 
        {6, {{0, "s11"}, {2, "s14"}, {3, "s13"}}}, 
        {7, {{0, "s11"}, {2, "s14"}, {3, "s13"}}}, 
        {8, {{2, "r20"}, {4, "r20"}, {6, "s28"}, {7, "r20"}, {8, "r20"}, {9, "r20"}, {10, "s27"}, {11, "r20"}}}, 
        {9, {{2, "r10"}, {4, "r10"}, {5, "s30"}, {6, "r10"}, {7, "r10"}, {8, "r10"}, {9, "r10"}, {10, "r10"}, {11, "r10"}}}, 
        {10, {{2, "r12"}, {4, "r12"}, {5, "r12"}, {6, "r12"}, {7, "r12"}, {8, "r12"}, {9, "r12"}, {10, "r12"}, {11, "r12"}}}, 
        {11, {{0, "s11"}, {2, "s14"}, {3, "s13"}}}, 
        {12, {{2, "r13"}, {4, "r13"}, {5, "r13"}, {6, "r13"}, {7, "r13"}, {8, "r13"}, {9, "r13"}, {10, "r13"}, {11, "r13"}}}, 
        {13, {{2, "r23"}, {4, "r23"}, {5, "r23"}, {6, "r23"}, {7, "r23"}, {8, "r23"}, {9, "r23"}, {10, "r23"}, {11, "r23"}}}, 
        {14, {{0, "s7"}, {2, "r26"}, {4, "r26"}, {5, "r26"}, {6, "r26"}, {7, "r26"}, {8, "r26"}, {9, "r26"}, {10, "r26"}, {11, "r26"}}}, 
        {15, {{4, "s33"}}}, 
        {16, {{4, "r5"}, {7, "r5"}, {8, "s20"}, {11, "s21"}}}, 
        {17, {{0, "s11"}, {2, "s14"}, {3, "s13"}}}, 
        {18, {{4, "r24"}, {7, "s22"}}}, 
        {19, {{0, "r22"}, {2, "r22"}, {3, "r22"}}}, 
        {20, {{0, "r16"}, {2, "r16"}, {3, "r16"}}}, 
        {21, {{0, "r19"}, {2, "r19"}, {3, "r19"}}}, 
        {22, {{0, "s11"}, {2, "s14"}, {3, "s13"}}}, 
        {23, {{4, "r9"}, {7, "r9"}}}, 
        {24, {{4, "r18"}, {7, "r18"}, {8, "s20"}, {11, "s21"}}}, 
        {25, {{0, "s11"}, {2, "s14"}, {3, "s13"}}}, 
        {26, {{0, "r8"}, {2, "r8"}, {3, "r8"}}}, 
        {27, {{0, "r1"}, {2, "r1"}, {3, "r1"}}}, 
        {28, {{0, "r14"}, {2, "r14"}, {3, "r14"}}}, 
        {29, {{2, "r2"}, {4, "r2"}, {5, "s30"}, {6, "r2"}, {7, "r2"}, {8, "r2"}, {9, "r2"}, {10, "r2"}, {11, "r2"}}}, 
        {30, {{0, "s11"}, {2, "s14"}, {3, "s13"}}}, 
        {31, {{2, "r4"}, {4, "r4"}, {5, "r4"}, {6, "r4"}, {7, "r4"}, {8, "r4"}, {9, "r4"}, {10, "r4"}, {11, "r4"}}}, 
        {32, {{2, "r3"}, {4, "r3"}, {6, "s28"}, {7, "r3"}, {8, "r3"}, {9, "r3"}, {10, "s27"}, {11, "r3"}}}, 
        {33, {{2, "r25"}, {4, "r25"}, {5, "r25"}, {6, "r25"}, {7, "r25"}, {8, "r25"}, {9, "r25"}, {10, "r25"}, {11, "r25"}}}, 
        {34, {{4, "s35"}, {8, "s20"}, {11, "s21"}}}, 
        {35, {{2, "r11"}, {4, "r11"}, {5, "r11"}, {6, "r11"}, {7, "r11"}, {8, "r11"}, {9, "r11"}, {10, "r11"}, {11, "r11"}}}, 
        {36, {{2, "r21"}, {8, "s20"}, {9, "r21"}, {11, "s21"}}}
    };

    std::unordered_map<int, std::unordered_map<int, int>> _sparse_goto_table = {
        {0, {{1, 2}, {9, 1}}}, 
        {2, {{3, 3}, {13, 5}}}, 
        {6, {{4, 36}, {7, 9}, {8, 10}, {12, 8}, {13, 12}}}, 
        {7, {{4, 16}, {7, 9}, {8, 10}, {12, 8}, {13, 12}, {14, 15}}}, 
        {8, {{0, 26}, {15, 25}}}, 
        {11, {{4, 34}, {7, 9}, {8, 10}, {12, 8}, {13, 12}}}, 
        {16, {{2, 19}, {5, 17}, {10, 18}}}, 
        {17, {{7, 9}, {8, 10}, {12, 32}, {13, 12}}}, 
        {18, {{11, 23}}}, 
        {22, {{4, 24}, {7, 9}, {8, 10}, {12, 8}, {13, 12}}}, 
        {24, {{2, 19}, {5, 17}}}, 
        {25, {{7, 29}, {8, 10}, {13, 12}}}, 
        {30, {{8, 31}, {13, 12}}}, 
        {32, {{0, 26}, {15, 25}}}, 
        {34, {{2, 19}, {5, 17}}}, 
        {36, {{2, 19}, {5, 17}}}
    };
    
    std::unordered_map<int, std::vector<std::string>> _sentence_index_grammar_tuple_mapping = {
        {23, {"0"}},
        {26, {"0"}},
        {11, {"1"}},
        {4, {"0", "1", "2"}},
        {2, {"0", "*1", "2"}},
        {3, {"0", "*1", "2"}},
        {24, {"0", "*1"}},
        {18, {"1"}},
        {5, {}},
        {9, {"*0", "*1"}},
        {25, {"0", "2"}},
        {21, {"0", "2"}},
        {6, {}},
        {15, {"*0", "1"}}
    };

    std::vector<int> _reduce_symbol_count = {1, 1, 3, 3, 3, 0, 0, 1, 1, 2, 1, 3, 1, 1, 1, 2, 1, 1, 2, 1, 1, 3, 1, 1, 2, 4, 1};

    std::vector<int> _reduce_non_terminal_index = {6, 0, 12, 4, 7, 10, 1, 9, 15, 10, 12, 8, 7, 8, 0, 1, 2, 3, 11, 2, 4, 3, 5, 8, 14, 13, 8};

    std::set<int> _none_grammar_tuple_reduce_set = {0, 1, 7, 8, 10, 12, 13, 14, 16, 17, 19, 20, 22};
};


template <class T>
class Interpreter {
public:
    using semantic_function = std::function<BosonSemanticsNode<T>(BosonSemanticsNode<T> &)>;

    Interpreter() = default;

    BosonSemanticsNode<T> execute(BosonGrammarNode &grammar_tree) {
        return this->_semantics_analysis(grammar_tree);
    }

    void register_action(const char *reduce_name, semantic_function function) {
        std::string reduce_name_string(reduce_name);
        this->register_action(reduce_name_string, function);
    }

    void register_action(std::string &reduce_name, semantic_function function) {
        this->_semantic_action_mapping[reduce_name] = function;
    }

private:
    std::unordered_map<int, std::string> _reduce_number_grammar_name_mapping = {
        {21, "set_variable"}, 
        {25, "function"}, 
        {3, "compute"}, 
        {2, "compute"}, 
        {4, "compute"}, 
        {11, "expression"}, 
        {26, "get_variable"}, 
        {23, "number"}
    };

    std::set<int> _naive_reduce_number_set = {1, 10, 12, 13, 14, 16, 17, 19, 20, 23, 26};

    std::unordered_map<std::string, semantic_function> _semantic_action_mapping{};

    BosonSemanticsNode<T> _semantics_analysis(BosonGrammarNode &grammar_tree) {
        std::string grammar_name{};
        if (this->_reduce_number_grammar_name_mapping.count(grammar_tree.get_reduce_number())) {
            grammar_name = this->_reduce_number_grammar_name_mapping[grammar_tree.get_reduce_number()];
        } else {
            grammar_name = "!grammar_hidden";
        }
        BosonSemanticsNode<T> semantics_node;
        for (auto &node: grammar_tree.children()) {
            if (!node.children().empty()) {
                semantics_node.append(this->_semantics_analysis(node));
            } else {
                BosonSemanticsNode<T> temp_node;
                temp_node.set_reduce_number(node.get_reduce_number());
                temp_node.set_text(node.get_text());
                semantics_node.append(temp_node);
            }
        }
        if (this->_semantic_action_mapping.count(grammar_name)) {
            return this->_semantic_action_mapping[grammar_name](semantics_node);
        } else if (this->_naive_reduce_number_set.count(grammar_tree.get_reduce_number())) {
            if (semantics_node.children().size() == 1) {
                return semantics_node[0];
            } else {
                return semantics_node;
            }
        } else {
            return semantics_node;
        }
    }
};
