/*
    Boson v1.5 - Grammar analyzer generator

        Author: ict
        Email:  ictxiangxin@hotmail.com
        Site:   https://github.com/ictxiangxin/boson

    File: "boson.hpp"
    These codes ware generated by the boson C++ code generator.
*/

#ifndef _BOSON_HPP_
#define _BOSON_HPP_

#include "token.hpp"
#include "lexer.hpp"
#include "grammar_node.hpp"
#include "grammar.hpp"
#include "parser.hpp"
#include "semantic_node.hpp"
#include "interpreter.hpp"

#endif
