/*
    Boson v1.5 - Grammar analyzer generator

        Author: ict
        Email:  ictxiangxin@hotmail.com
        Site:   https://github.com/ictxiangxin/boson

    File: "grammar.hpp"
    These codes ware generated by the boson C++ code generator.
*/

#ifndef _BOSON_GRAMMAR_HPP_
#define _BOSON_GRAMMAR_HPP_

#include "grammar_node.hpp"

namespace boson {
    class BosonGrammar {
    public:
        BosonGrammar() = default;

        BosonGrammarNode &get_grammar_tree() {
            return this->_grammar_tree;
        }

        void set_grammar_tree(BosonGrammarNode &grammar_tree) {
            this->_grammar_tree = grammar_tree;
        }

        int get_error_index() const {
            return this->_error_index;
        }

        void set_error_index(int error_index) {
            this->_error_index = error_index;
        }

        int no_error_index() const {
            return this->_no_error_index;
        }

    private:
        BosonGrammarNode _grammar_tree;
        int _error_index = -1;
        int _no_error_index = -1;
    };
}

#endif
