/*
    Boson v1.5 - Grammar Analyzer Generator

        Author: ict
        Email:  ictxiangxin@hotmail.com
        Site:   https://github.com/ictxiangxin/boson

    File: "lexer.hpp"
    These codes ware generated by the boson C++ code generator.
*/

#ifndef _BOSON_LEXER_HPP_
#define _BOSON_LEXER_HPP_

#include <functional>
#include <vector>
#include <set>
#include <unordered_map>
#include "token.hpp"

namespace boson {
    class Tokenizer {
    public:
        using lexical_function = std::function<string_t &(string_t &)>;

        Tokenizer() = default;

        std::vector<Token> &token_list() {
            return this->_token_list;
        }

        int line() const {
            this->_line;
        }

        void skip() {
            this->_skip = true;
        }

        void newline() {
            this->_line++;
        }

        int error_index() const {
            return _error_index;
        }

        int no_error_index() const {
            return _no_error_index;
        }

        int tokenize(string_t text) {
            this->_token_list.clear();
            this->_line = 1;
            int state = this->_start_state;
            string_t token_string{};
            int index = 0;
            while (index < text.length()) {
                char_t character = text[index];
                index++;
                bool get_token = false;
                if (this->_non_greedy_state_set.count(state)) {
                    get_token = true;
                }
                if (this->_compact_move_table.count(state)) {
                    std::vector<std::tuple<int, std::set<char_t>, std::vector<std::tuple<char_t, char_t>>, int>> state_move_table = this->_compact_move_table[state];
                    unsigned long i;
                    for (i = 0; i < state_move_table.size(); i++) {
                        std::tuple<int, std::set<char_t>, std::vector<std::tuple<char_t, char_t>>, int> compact_table = state_move_table[i];
                        int attribute = std::get<0>(compact_table);
                        std::set<char_t> &character_set = std::get<1>(compact_table);
                        std::vector<std::tuple<char_t, char_t>> &range_list = std::get<2>(compact_table);
                        int next_state = std::get<3>(compact_table);
                        bool condition;
                        if (attribute == 2) {
                            condition = !character_set.count(character);
                            for (auto & range : range_list) {
                                condition &= character < std::get<0>(range) || character > std::get<1>(range);
                            }
                        } else {
                            condition = character_set.count(character);
                            if (attribute == 1 && this->_character_set.count(character) == 0) {
                                condition = true;
                            }
                            for (auto & range : range_list) {
                                if (condition || (std::get<0>(range) <= character && character <= std::get<1>(range))) {
                                    condition = true;
                                    break;
                                }
                            }
                        }
                        if (condition) {
                            token_string += character;
                            state = next_state;
                            break;
                        }
                    }
                    if (i == state_move_table.size()) {
                        if (this->_end_state_set.count(state)) {
                            get_token = true;
                        } else {
                            this->_error_index = index - 1;
                            return this->_error_index;
                        }
                    }
                } else {
                    if (this->_end_state_set.count(state)) {
                        get_token = true;
                    } else {
                        this->_error_index = index - 1;
                        return this->_error_index;
                    }
                }
                if (get_token) {
                    this->_generate_token(state, token_string);
                    token_string = "";
                    state = this->_start_state;
                    index--;
                }
            }
            if (this->_end_state_set.count(state)) {
                this->_generate_token(state, token_string);
            } else {
                this->_error_index = index - 1;
                return this->_error_index;
            }
            this->_token_list.emplace_back("", this->_line, "$");
            return this->_error_index;
        }

        void register_function(std::string &function_name, lexical_function &function) {
            this->_lexical_function[function_name] = function;
        }

    private:
        std::vector<Token> _token_list{};
        int _line = 1;
        int _error_index = -1;
        int _no_error_index = -1;
        bool _skip = false;
        std::unordered_map<int, std::vector<std::tuple<int, std::set<char_t>, std::vector<std::tuple<char_t, char_t>>, int>>> _compact_move_table = {
            {0, {
                {0, {'_'}, {{'A', 'Z'}, {'a', 'z'}}, 1},
                {0, {}, {{'0', '9'}}, 2},
                {0, {'\t', ' '}, {}, 3},
                {0, {'\r'}, {}, 4},
                {0, {'\n'}, {}, 5},
                {0, {'='}, {}, 6},
                {0, {'('}, {}, 7},
                {0, {','}, {}, 8},
                {0, {')'}, {}, 9},
                {0, {'^'}, {}, 10},
                {0, {'*'}, {}, 11},
                {0, {'/'}, {}, 12},
                {0, {'+'}, {}, 13},
                {0, {'-'}, {}, 14}
            }},
            {4, {
                {0, {'\n'}, {}, 5}
            }},
            {3, {
                {0, {'\t', ' '}, {}, 3}
            }},
            {2, {
                {0, {'.'}, {}, 15},
                {0, {}, {{'0', '9'}}, 2}
            }},
            {15, {
                {0, {}, {{'0', '9'}}, 15}
            }},
            {1, {
                {0, {'_'}, {{'0', '9'}, {'A', 'Z'}, {'a', 'z'}}, 1}
            }}
        };
        std::set<char_t> _character_set = {'K', 'p', '6', 'P', 'e', '^', 'q', 'X', '2', 'a', 'L', 'U', 't', 's', 'h', 'D', 'V', '1', '\r', 'u', '\t', 'l', 'O', 'x', 'B', '\n', 'I', 'E', '_', 'y', 'Y', 'W', 'A', '=', 'S', '/', 'z', 'm', '-', '+', 'f', 'i', 'T', ')', 'k', 'j', 'G', 'R', 'N', 'v', 'r', '0', '3', ' ', 'Z', 'd', '(', 'g', 'c', 'M', '9', '7', '8', 'w', 'n', 'H', 'F', '4', '5', '.', ',', 'J', 'b', 'C', 'o', '*', 'Q'};
        int _start_state = 0;
        std::set<int> _end_state_set = {1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
        std::unordered_map<int, std::string> _lexical_symbol_mapping = {
            {1, "t_symbol"},
            {2, "t_number"},
            {3, "skip"},
            {5, "newline"},
            {6, "!symbol_1"},
            {7, "!symbol_2"},
            {8, "!symbol_3"},
            {9, "!symbol_4"},
            {10, "!symbol_5"},
            {11, "!symbol_6"},
            {12, "!symbol_7"},
            {13, "!symbol_8"},
            {14, "!symbol_9"},
            {15, "t_number"}
        };
        std::set<int> _non_greedy_state_set = {};
        std::unordered_map<std::string, std::vector<std::string>> _symbol_function_mapping = {
            {"skip", {"skip"}},
            {"newline", {"skip","newline"}}
        };
        std::unordered_map<std::string, lexical_function> _lexical_function{};

        string_t &_invoke_lexical_function(std::string &symbol, string_t &token_string) {
            this->_skip = false;
            if (this->_symbol_function_mapping.count(symbol)) {
                for (const auto& function : this->_symbol_function_mapping[symbol]) {
                    if (this->_lexical_function.count(function)) {
                        token_string = this->_lexical_function[function](token_string);
                    } else if (function == "skip") {
                        this->skip();
                    } else if (function == "newline") {
                        this->newline();
                    }
                }
            }
            return token_string;
        }

        void _generate_token(int state, string_t &token_string) {
            std::string symbol;
            if (this->_lexical_symbol_mapping.count(state)) {
                symbol = this->_lexical_symbol_mapping[state];
            } else {
                symbol = "!symbol";
            }
            token_string = this->_invoke_lexical_function(symbol, token_string);
            if (!this->_skip) {
                this->_token_list.emplace_back(token_string, this->_line, symbol);
            }
        }
    };
}

#endif
