/*
    Boson v1.5 - Grammar analyzer generator

        Author: ict
        Email:  ictxiangxin@hotmail.com
        Site:   https://github.com/ictxiangxin/boson

    File: "token.hpp"
    These codes ware generated by the boson C++ code generator.
*/

#ifndef _BOSON_TOKEN_HPP_
#define _BOSON_TOKEN_HPP_

namespace boson {
    class Token {
    public:
        Token() = default;

        Token(std::string &text, const int line, std::string &symbol): text(text), line(line), symbol(symbol) {};

        Token(const char *text, const int line, const char *symbol): text(text), line(line), symbol(symbol) {};

        Token(const char *text, const int line, std::string &symbol): text(text), line(line), symbol(symbol) {};

        Token(std::string &text, const int line, const char *symbol): text(text), line(line), symbol(symbol) {};

        std::string text{};
        int line = -1;
        std::string symbol{};
    };
}

#endif
